version: '3'

services:
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=djangodb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=127.0.0.1
            - POSTGRES_PORT=5432
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - pgdata:/var/lib/posrgresql/data



volumes:
    pgdata: