version: '3'

services:
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=djangodb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=127.0.0.1
            - POSTGRES_PORT=5432
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - pgdata:/var/lib/posrgresql/data

    web:
        build: .
        container_name: web
        command: >
            bash -c "python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
        ports:
            - 10555:8000
        volumes:
            - .:/code
        depends_on:
            - db

volumes:
    pgdata: